### ISSUE TITLE
Height of the skeleton/animation

### ISSUE THREAD

**Issue by RobertBlackhart** [bp74/StageXL_Spine#1]
I think I may be missing something, but how do I get the height of the current animation? Querying the SkeletonAnimation.height property returns 0. Do I need to set this myself somewhere? I see there is a defined width and height property in the Spine skeleton file

`"skeleton": { "hash": "MTPtKW7qyAoD4ZSH4DI9m6s5wmY", "spine": "3.2.01", "width": 105, "height": 221.63 },`

That looks about right to me. How do I get access to this value at runtime (not sure I want to hard code it)? Especially because it might change depending on the applied scale.

**Comment by bp74** [comment]
Hi Robert,

Thanks for the question. There is an easy answer and a more advanced answer:

You can access the width and height of the skeleton data like this:

```
var spineJson = resourceManager.getTextFile("hero");
var textureAtlas = resourceManager.getTextureAtlas("hero");
var attachmentLoader = new TextureAtlasAttachmentLoader(textureAtlas);
var skeletonLoader = new SkeletonLoader(attachmentLoader);
var skeletonData = skeletonLoader.readSkeletonData(spineJson);

var width = skeletonData.width;
var height = skeletonData.height;
```

This will give you the width and height that is defined in the json file. But it would be nice to access the width and height of the skeleton animation (the actual display object) too, right?

To get the width and height of the skeleton animation we would need to know the bounds of the animation. You can define bounding boxes and get those bounding boxes at runtime (see the "spinboy-old" example, where a bounding box is defined for the head of the boy). In a more advanced scenario we could calculate a polygon for the bounds of a meshes. To make this easier we would need to extend the API a little bit. I should probably add more priority to this feature on my ToDo list :)

To make a long story short, for a correct value of width and height we would need to use this bounds calculations. Currently both getters return 0 because we don't calculate the actual size of the skeleton animation (the display object). The same is true for hit-tests because we don't calculate the bounds. That said, even if we add this feature we probably turn it of by default and you have to opt-in because calculation the bounds will costs some CPU cycles. 

Hope this helps and your feedback is welcome!

**Comment by RobertBlackhart** [comment]
So I'm not able to test it out right now, but looking at the SkeletonBounds class it looks like all I'd need to do to get an accurate width and height at runtime was to have an instance of it and call update giving it my current Skeleton object anytime it changes. Then I could query it for width and height. This seems like a solution to my current problem.

As far as the automatic calculation of the bounds, I would put a vote in for that feature. If for no other reason than it is a little confusing why the width and height would return 0 on a fully loaded object. I see the code now where you have the comment about the NYI opt-in feature, but I'm not sure the consumers of your library should need to read that far to understand the behavior.

Thanks again for helping me with my current issue.
